

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Inventario.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Registro_TiendasEntities3 : DbContext
{
    public Registro_TiendasEntities3()
        : base("name=Registro_TiendasEntities3")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Categorias> Categorias { get; set; }

    public virtual DbSet<Encargado> Encargado { get; set; }

    public virtual DbSet<Marca> Marca { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<Rol> Rol { get; set; }

    public virtual DbSet<Tienda> Tienda { get; set; }

}

}

